# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder and final in one stage
FROM node:lts-alpine AS build
WORKDIR /app
# Copy source
COPY package.json yarn.lock tsconfig.json ./
COPY src ./src
# Install dependencies and build
RUN yarn install --frozen-lockfile && yarn run build

# Production image
FROM node:lts-alpine
WORKDIR /app
# Copy production dependencies
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile
# Copy build artifacts
COPY --from=build /app/build ./build

# Default command
ENTRYPOINT ["node", "build/index.js"]
