# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json yarn.lock tsconfig.json ./
COPY src ./src
RUN apk add --no-cache python3 make g++ \
 && yarn install --frozen-lockfile \
 && yarn run build

# Final image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and install production dependencies
COPY --from=builder /app/build ./build
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile

ENTRYPOINT ["node", "build/index.js"]
